cp /Users/rpruim/public_html/fast/R/Rchunk/iris-str.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/iris-head.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/iris-tail.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/iris-subset.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/iris-vector.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/iris-vector2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/iris-reload.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/iris-table.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/iris-table2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/iris-logical.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/iris-cut.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/iris-cut2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/iris-histo-density.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/iris-condition.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/iris-histo-subset.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/faithful-histogram.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/iris-mean-median.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/iris-Hmisc-summary.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/faithful-mean-median.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/faithful-stem.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/pulse-histo.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/number-prob.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/intro-quantile.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/intro-quantile05a.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/intro-quantile05b.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/faithful-quantile.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/iris-bwplot.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/fivenum-a.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/fivenum-b.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/bwplot-iqr-rule.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/intro-dispersion02.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/pitching2005-era.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/intro-deathPenalty01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/intro-deathPenalty02.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/intro-deathPenalty03.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/utilities.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/utilities-ccfpday.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/utilities-ccfpday.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/utilities-temp.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/utilities-price.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/births.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/dice-sample-space.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/print-sums.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/choose.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/cards-full-house.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/cards-two-pair.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/cards-three-kind.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/birthday-problem.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/cards-same-color.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/bayesDisease.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/statistics.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/acceptance-sampling.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/acceptance-sampling-binomial.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/acceptance-sampling-nbinom.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/three-straight-heads.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/mastermind.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/cards-flush2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/socks.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/pmf-plot.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/binom-demo01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/binom-freddy01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/nbinom-first-example01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/deMere.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/amy.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/Hamming.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/freethrow04.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/freethrow02.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/freethrow03.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/multiple-choice01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/playoffs-part.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/playoffs01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/binomtest-lady-tea01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/binomtest-lady-tea02.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/binomtest-hugo01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/binomtest-hugo02.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/binomtest-hugo03.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/spinner.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/Gus.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/mendel.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/beetles.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/binomtest-power01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/binomtest-power02.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/binomtest-power03.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/binomtest-power05.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/binomtest-power06.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/prob-power01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/discDists-mean-coins01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/discDists-mean-coins02.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/discDists-var-example01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/varExampleFromTable01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/negbinomial-var.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/search-expval.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/alice-bob01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/poisson-customers-1.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/poisson-customers-2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/fumbles.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/prob-pois-01s.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/prob-pois-01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/youthSoccer01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/ladyTeaHyper01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/ladyTeaHyperBinom01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/fisher-twins1.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/fisher-twins2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/ticket01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/ticket02.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/ticket01-02.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/firstDigit.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/kings-and-queens.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/kings-and-hearts.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/conditional-urn.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/pdf-example01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/prob-dist01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/prob-dist02.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/cauchy01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/cont-uniform.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/runif.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/cdf-method01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/bank01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/pois-sim.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/fumbles02.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/prob-cdf01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/prob-cdf02.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/prob-traffic-01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/normal01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/normal01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/normal-sat.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/sat-rescale.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/sat-percentile.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/prob-middle-of-dist.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/prob-weibull-01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/prob-beta-01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/kde01-data.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/kde01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/kde02.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/faithful-kde.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/normal-quantile-01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/normal-quantile-01p.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/normal-quantile-02.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/normal-quantile-03.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/normal-quantile-04.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/qq-weibull-01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/qq-exp-01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/joint02.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/mom-unif1-sim.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/mom-exp.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/moment.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/mom-norm.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/mom-beta01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/mom-beta01a.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/sample-means.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/mom-beta01-sim.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/mom-beta02-sim.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/miaa-ft-betas.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/miaa-ft-beta.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/mom-life01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/mom-life02.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/sample-srs.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/law-large-numbers.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/lln-cauchy.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/lln-cauchy-seed.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/clt-prob02.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/clt-prob-finite-samples.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/clt-prob-finite-sample.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/unif12.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/betaCLT.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/continuity-correction.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/binomial-ztest.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/z-test.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/free-weights.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/z-ci.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/CI-vis.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/simulateCI.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/simulateCI-unif.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/simulateCI-beta.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/simulateCI-exp.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/99CI.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/uvec-prob01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/tCI-01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/t-test-01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/t-test-iris.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/uvec-prob02.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/sepal-width-cint.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/sepal-length-cint.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/sepal-ratio-cint.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/prob-shoe-size-CI.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/t-simulations.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/t-robust-heavytails.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/t-robust-exp.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/t-robust-qq.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/helium-football.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/helium-football-sign.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/endurance-paired.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/Joes-coin.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/golfballs-range.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/fisher-twins-perm.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/fisher-twins-exact.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/fisher-twins-ci.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/iris-perm.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/iris-perm-versi.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/prob5-09.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/plant-density.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/plant-density2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/baseballBA1.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/baseballBA2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/baseballBA3.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/baseballBA4.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/mle-faithful.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/mle-faithful2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/mle-multinom.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/mle-unif-nlmax.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/hwe-mle.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/mle-pois.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/mle-pois2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/lrt-faithful.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/laplace.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/lrt-laplace.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/faithful-ci.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/golfballs-max.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/golfballs-pearson-sim.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/golfballs-pearson.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/golfballs-lrt.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/golfballs-complex.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/fit-bugs-pois.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/fit-bugs-pois2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/fit-exp.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/GOF.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/gof-gamma.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/gof-weibull.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/hwe-gof.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/fisher-plants.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/mendel-pea-cross.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/smoke-xtabs.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/smoke-manual.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/smoke-test.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/smoke-test-attr.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/smoke-test2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/smoke-mosaic.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/smoking-ads.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/smoking-ads2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/smoking-bbs.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/smoking-bbs2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/phs.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/chisq-twins.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/amd.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/fusion1-merge.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/fusion1-xtabs-geno.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/fusion1-xtabs-dose.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/fusion1m-3models.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/nfl-prep.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/nfl-bt.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/nfl-post.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/nfl-post2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/ncaa2010-bt-prep.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/ncaa2010-bt-fit.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/ncaa2010-bt-look.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/ncaa2010-bt-look2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/ncaa2010-bt-hc-fit.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/ncaa2010-bt-hc-look.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/ncaa2010-bt-hc-look2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/ncaa2010-compare.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/binom-credible.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/binom-credible2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/binom-bayes-pval.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/bayes-normal.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/lm-demo1.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/lm-demo2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/lm-demo3.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/lm-demo-vector.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/lm-demo-matrix.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/lm-demo-matrix2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/lm-demo-hat.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/lm-trebuchet2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/lm-elasticband.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/lm-trebuchet2-summary.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/lm-trebuchet2-ci.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/confint-lm.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/lm-elasticband-ci.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/anova-trebuchet2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/lm-trebuchet2-summary.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/anova-elasticband.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/trebuchet2-predict.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/trebuchet2-plot2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/elasticband-predict.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/lm-star.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/lm-star-dfbeta.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/balldrop.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/balldrop-trans.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/balldrop-avg.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/lm-soap.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/lm-soap-trans.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/lm-soap-ci.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/trebuchet2-effects.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/anova-from-lm.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/anova-from-lm-sol.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/act-gpa.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/drag.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/taste-favstats.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/lm-taste.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/lm-taste-ci.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/lm-taste-rescale.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/lm-corn.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/paired-corn.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/tirewear.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/tirewear2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/tirewear-ttest.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/tirewear-sign.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/oats-variety.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/t-corn.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/t-test-taste.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/power-t-test01a.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/power-t-test01b.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/power-t-test01c.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/power-t-test01d.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/power-t-test02.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/glm-orings.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/glm-orings-predict.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/glm-orings-predict2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/runswins-look.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/runswins-glm.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/runswins-glm2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/glm-orings-ci.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/glm-orings-ci2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/runswins-lm.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/buckthorn.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/buckthorn-probit.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/lm-simulate1.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/lm-simulate2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/lm-simulate3.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/lm-simulate4.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/punting-lm.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/punting2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/punting-resid.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/punting-predict.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/concrete-lm1.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/concrete-lm1a.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/concrete-lm1b.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/concrete-lm1c.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/concrete-minus.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/concrete-minus-dot.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/concrete-minus-adj.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/concrete-minus2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/concrete-minus3.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/small-lmfit.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/concrete-models.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/concrete-mct.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/concrete-summary.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/concrete-confint1.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/concrete-aic.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/concrete-plot1.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/additive.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/utilities-lm1.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/utilities-presid.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/utilities-kwh.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/gpa1.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/gpa2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/gpa3.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/gpa4.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/gpa-mct1.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/gpa-mct.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/pheno-weight-prob.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/students1.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/pheno-weight.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/pheno-weight-confint.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/pheno-weight-resid.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/coag-look.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/coag-lm.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/coag-mct.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/coag-anova.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/coag-geom.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/coag-anova.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/coag-lm2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/coag-alt.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/airp-summary.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/airp-anova.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/petstress.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/airp-modcomp1.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/airp-modcomp2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/airp-modcomp2a.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/airp-vectors.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/coag-lm.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/airp-TukeyHSD.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/airp-glht.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/coag-TukeyHSD.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/coag-glht.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/airp-glht1.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/airp-glht1a.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/airp-glht1b.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/airp-glht1c.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/airp-glht1d.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/cholesterol.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/cholesterol-HSD.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/chol-contrasts.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/coag-dunnet.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/taste-anova.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/cholesterol-comb.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/bugs.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/taste-xtab.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/taste-2way-anova.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/taste-2way-lm.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/taste-2way-matrix.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/taste-mct.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/noise-math1.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/noise-math2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/noise-math-plots.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/poison.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/poison-resid.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/poison-trans.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/poison-trans-anova.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/palettes-1way.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/palettes-blocking.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/palettes-summary.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/palettes-percs.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/palettes-perc.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/utilities-kwh-int.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/utilities-kwh-int2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/utilities-uniroot.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/utilities-month.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/utilities-month2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/utilities-month3.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/domedata.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/domedata-step.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/seatpos-lm.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/seatpos-vif.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/seatpos-cor.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/seatpos-lm2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/seatpos-pc.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/seatpos-step.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/ice-baseline-summary.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/ice-baseline-int.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/ice-baseline-add.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/ice-baseline-tukey.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/ice-treatment.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/ice-treatment-intr.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/ice-diff.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/fusion1-merge.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/fusion1-xtabs-dose.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/fusion1-glm1.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/fusion1-glm1-or.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/fusion1-glm1-sum.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/fusion1-glm1-mut.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/fusion1-glm1-dev.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/fusion1-glm2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/fusion1-glm2-dev.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/step.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/rat-anova.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/rat-1way.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/concrete-load.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/concrete-summary.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/concrete-perm-f.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/concrete-perm-t.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/smoke-perm.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/rat-liver.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/rabbit.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/eggprod.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/faithful-stemleaf.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/s/rpruim/public_html/fast/R/Rprofile.txt inst/snippet/
cp /Users/rpruim/public_html/fast/R/s/rpruim/.Renviron inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/help01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/apropos.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/args.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/packageData-iris.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/iris-help.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/read-table.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/read-sas.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/scan.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/dataframe.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/generatingData01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/generatingData02.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/writingData.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/savingData.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/mode01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/access.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/attributes.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/whatIsThis.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/asYouLikeIt.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/vectors01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/vectors01a.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/vectors02.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/vectors02a.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/vectors03.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/vectors04a.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/vectors04b.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/vectors04c.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/vectors04d.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/iris-vectors.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/iris-Hmisc-summary-q.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/iris-xtabs.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/adding-variable.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/adding-variable2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/traffic-reshape.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/iris-xyplot01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/iris-histogram01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/iris-histogram02.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/iris-bwplot01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/iris-bwplot02.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/qqmath01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/qqmath03.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/qqmath04.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/iris-splom.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/iris-splom02.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/set-pch.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/fastR-theme.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/defFun01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/defFun02.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/defFun02-cat.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/defFun02a.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/defFun03.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/defFun04.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/defFun11.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/defFun12.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/histogram-rug-density.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/histogram-rug-density-grid.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/plot.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/plot-methods.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/xplot.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/xqqmath.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/xqqmath-example.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/whats-up.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/whats-up.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/sum-ssols.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/some-sums.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/vec-mult.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/vec-mult2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/dot.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/vec-dotprod.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/vec-proj.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/vdecomp.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/vector-decomp1.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/vector-decomp2.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/vector-decomp3.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/projections-01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/orthonormal-s1.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/mat-dim.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/mat-checkdim.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/matrix.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/matrix-recycle.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/mat-bind.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/as-matrix.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/matrix-t.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/mat-mult.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/mat-dot.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/mat-outer.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/mat-outer-fun.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/mat-solve.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/review-data.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/moments-binom.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/moments-exp.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/test-coin-review.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/test-coin-power01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/test-coin-power02.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/test-coin-power03.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/min-of-unif01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/min-of-unif02.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/mix-normals01.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/mix-normals02.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/lognormal.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/review-faithful.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/moments-function.Rchunk inst/snippet/
cp /Users/rpruim/public_html/fast/R/Rchunk/moments-function-cont.Rchunk inst/snippet/
