# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logistic_only <- function(x,y) {
  .Call('fastR_logistic_only', PACKAGE = 'fastR',x,y)
}

poisson_only <- function(x,y) {
  .Call('fastR_poisson_only', PACKAGE = 'fastR',x,y)
}

colMedians <- function(x) {
  .Call('fastR_colmeds', PACKAGE = 'fastR',x)
}

nth <- function(x,k) {
  .Call('fastR_nth', PACKAGE = 'fastR',x,k)
}